version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dike
    binary: dike
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - { goos: windows, goarch: arm64 }
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/dike:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/dike:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64,linux/arm64"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true
